### ISSUE TITLE
Package for OPAM

### ISSUE THREAD

**Issue by tmcgilchrist** [avsm/ocaml-lens#2]
Is there any interest in packaging this up for OPAM?

**Comment by m2ym** [comment]
:+1:

**Comment by avsm** [comment]
Sorry I missed your original report.  I extracted this out of @astrada's code base, so I'll defer to him in case he wants to maintain this separately first.

**Comment by pdonadeo** [comment]
@avsm I have an half-done OPAM package... since a couple of months :-)

I'm going to commit today and pull a request.

**Comment by pdonadeo** [comment]
@avsm can you create a tag 1.0.0 and a release on GitHub, so I can link the tarball in the url file?

**Comment by avsm** [comment]
@pdonadeo I feel a little odd putting this package up since none of it is my code, just all @astrada's.  So it would be good if he could either ack this to indicate it's ok, or take over the repo, or something in between.  And thanks for taking the time to create the OPAM package!

**Comment by astrada** [comment]
Sure, @pdonadeo asked my permission. Feel free to upload the package. Thanks!

**Comment by pdonadeo** [comment]
@avsm @astrada ok, I'll use my fork for the release and the OPAM package.

**Comment by pdonadeo** [comment]
Just submitted a pull request to ocaml/opam-repository#3856

I hope it will work, first time since a long time...

**Comment by foretspaisibles** [comment]
Since https://github.com/ocaml/opam-repository/pull/3856 has been merged, we probably could close this! :)
